
title: My Resume
url: 'http://onuratakan.github.io/'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Onur Atakan ULUSOY  ## put your name
title: 'BLOCKCHAIN EXPERT &amp; DEVELOPER'  ## your title
location: Turkey


## Social Profiles
facebook: https://www.facebook.com/atakan.ulusoy.94695/  ## your facebook account url
#twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://linkedin.com/in/onur-atakan-ulusoy  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
